export const API_PRODUCT="API_PRODUCT";

export const ADD_LIST_FAVORITES="ADD_LIST_FAVORITES"
export const REMOVE_LIST_FAVORITES="REMOVE_LIST_FAVORITES"


export const ADD_LIST_SHOP="ADD_LIST_SHOP"
export const ADD_ALL_LIST_SHOP="ADD_ALL_LIST_SHOP"
export const REMOVE_LIST_SHOP="REMOVE_LIST_SHOP"
export const REMOVE_ALL_LIST_FAVORITES="REMOVE_ALL_LIST_FAVORITES"
export const ADDITION_LIST_SHOP="ADDITION_LIST_SHOP"
export const DEDUCTION_LIST_SHOP="DEDUCTION_LIST_SHOP"
